-- Milestone 3, checkpoint 1: PostgreSQL version of the Applications schema
-- completed in Milestones 1 and 2.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table public.applications (
  id bigint generated by default as identity primary key,
  company_name varchar(150) not null,
  job_title varchar(150) not null,
  job_url varchar(2048),
  source varchar(100),
  status varchar(32) not null default 'saved'
    check (status in (
      'saved',
      'applied',
      'screening',
      'interviewing',
      'offered',
      'rejected',
      'ghosted',
      'withdrawn'
    )),
  applied_at timestamptz,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create trigger applications_set_updated_at
before update on public.applications
for each row execute function public.set_updated_at();

alter table public.applications enable row level security;

-- Browser access remains blocked. The Cloudflare API will use the server-only
-- service role until user authentication and ownership policies are added.
grant usage on schema public to service_role;
grant select, insert, update, delete on public.applications to service_role;
grant usage, select on sequence public.applications_id_seq to service_role;
