alter table public.applications
  add column location varchar(150),
  add column work_mode varchar(32),
  add column employment_type varchar(64),
  add column experience_min numeric(4,1),
  add column experience_max numeric(4,1),
  add column salary_min numeric(14,2),
  add column salary_max numeric(14,2),
  add column salary_currency char(3),
  add column salary_period varchar(32),
  add column expected_salary numeric(14,2),
  add column next_action varchar(255),
  add column follow_up_at timestamptz;

create table public.outreach (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid()
    references auth.users(id) on delete cascade,
  contact_name varchar(150),
  contact_title varchar(150),
  company_name varchar(150) not null,
  contact_email varchar(320) not null,
  sender_email varchar(320) not null,
  subject varchar(500) not null,
  resume_filename varchar(255),
  linkedin_url varchar(2048),
  source varchar(100) not null default 'Gmail',
  contact_source varchar(100),
  outreach_type varchar(64),
  related_application_id bigint references public.applications(id) on delete set null,
  status varchar(32) not null default 'draft'
    check (status in ('draft', 'sent', 'follow_up_due', 'replied', 'closed')),
  sent_at timestamptz,
  follow_up_at timestamptz,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index outreach_user_created_idx
on public.outreach (user_id, created_at desc);

create index outreach_user_follow_up_idx
on public.outreach (user_id, status, follow_up_at);

create trigger outreach_set_updated_at
before update on public.outreach
for each row execute function public.set_updated_at();

alter table public.outreach enable row level security;
revoke all on public.outreach from anon;
grant select, insert, update, delete on public.outreach to authenticated;
grant usage, select on sequence public.outreach_id_seq to authenticated;

create policy "Users can read their outreach"
on public.outreach for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their outreach"
on public.outreach for insert to authenticated
with check (
  (select auth.uid()) = user_id
  and (
    related_application_id is null
    or exists (
      select 1 from public.applications
      where applications.id = related_application_id
        and applications.user_id = (select auth.uid())
    )
  )
);

create policy "Users can update their outreach"
on public.outreach for update to authenticated
using ((select auth.uid()) = user_id)
with check (
  (select auth.uid()) = user_id
  and (
    related_application_id is null
    or exists (
      select 1 from public.applications
      where applications.id = related_application_id
        and applications.user_id = (select auth.uid())
    )
  )
);

create policy "Users can delete their outreach"
on public.outreach for delete to authenticated
using ((select auth.uid()) = user_id);
