create table public.application_updates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  application_id bigint not null references public.applications(id) on delete cascade,
  status varchar(32) not null check (status in ('applied', 'screening', 'interviewing', 'offered', 'rejected', 'ghosted', 'withdrawn')),
  title varchar(150) not null,
  happened_at timestamptz not null,
  details text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index application_updates_user_application_date_idx
  on public.application_updates (user_id, application_id, happened_at desc);

create trigger application_updates_set_updated_at
  before update on public.application_updates
  for each row execute function public.set_updated_at();

alter table public.application_updates enable row level security;
revoke all on public.application_updates from anon;
grant select, insert, update, delete on public.application_updates to authenticated;
grant usage, select on sequence public.application_updates_id_seq to authenticated;

create policy "Users can read their application updates"
  on public.application_updates for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their application updates"
  on public.application_updates for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (select 1 from public.applications
      where applications.id = application_id
        and applications.user_id = (select auth.uid()))
  );

create policy "Users can edit their application updates"
  on public.application_updates for update to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (select 1 from public.applications
      where applications.id = application_id
        and applications.user_id = (select auth.uid()))
  );

create policy "Users can delete their application updates"
  on public.application_updates for delete to authenticated
  using ((select auth.uid()) = user_id);
