-- Admin membership is granted only by a database administrator.
create table public.admin_memberships (
  user_id uuid primary key references auth.users(id) on delete cascade,
  granted_at timestamptz not null default now()
);
alter table public.admin_memberships enable row level security;
revoke all on public.admin_memberships from anon, authenticated;

create table public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id),
  action varchar(64) not null,
  created_at timestamptz not null default now()
);
create index admin_audit_created_idx on public.admin_audit_logs (created_at desc);
alter table public.admin_audit_logs enable row level security;
revoke all on public.admin_audit_logs from anon, authenticated;
revoke all on sequence public.admin_audit_logs_id_seq from anon, authenticated;

create function public.admin_access()
returns boolean
language sql
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admin_memberships where user_id = (select auth.uid())
  );
$$;
revoke all on function public.admin_access() from public, anon;
grant execute on function public.admin_access() to authenticated;

create function public.admin_summary()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not public.admin_access() then
    raise exception 'Admin access is required.' using errcode = '42501';
  end if;

  insert into public.admin_audit_logs (admin_user_id, action)
  values ((select auth.uid()), 'view_dashboard');

  return jsonb_build_object(
    'members', (select count(*) from public.profiles),
    'new_members_7d', (select count(*) from public.profiles where created_at >= now() - interval '7 days'),
    'applications', (select count(*) from public.applications),
    'outreach', (select count(*) from public.outreach),
    'outreach_sent', (select count(*) from public.outreach where sent_at is not null),
    'outreach_replied', (select count(*) from public.outreach where status = 'replied'),
    'stages', coalesce((
      select jsonb_object_agg(status, total) from (
        select status, count(*) as total from public.applications group by status
      ) stage_totals
    ), '{}'::jsonb),
    'recent_admin_activity', coalesce((
      select jsonb_agg(row_to_json(log_row)) from (
        select action, created_at from public.admin_audit_logs
        order by created_at desc limit 6
      ) log_row
    ), '[]'::jsonb)
  );
end;
$$;
revoke all on function public.admin_summary() from public, anon;
grant execute on function public.admin_summary() to authenticated;
